<?php
// h //
$ped = "Pearson Education Deutschland";
$buch = "Bet";
$erscheinungsjahr = 2006;
$pearson = $ped;
$erscheinungsjahr1 = 2007;
print($buch);
print("<br />");
print($pearson);
print("<br />");
print($erscheinungsjahr);
print("<br />");
print($erscheinungsjahr1);
print("<br />");
?>

<?php
$Caden = 14;
$Van = 13;
$Long = 13;
print("Caden + Van + Long = ");
print($Caden + $Van + $Long); 
print("<br/>");

?>

<?php
$Caden = 14;
$Van = 13;
$Long = 13;
print("Caden - Van - Long = ");
print($Caden - $Van - $Long); 
print("<br/>");
?>

<?php
$Caden = 14;
$Van = 13;
$Long = 13;
print("Caden * Van * Long = ");
print($Caden * $Van * $Long); 

?>